# action.yml
name: 'Caretaker Project Manager'
description: 'A simple action to automatically manage projects and issues for PRs.'
inputs:
  command:
    description: 'The command to execute for Caretaker'
    required: true
    default: ''
  token:  # id of input
    description: 'GitHub token.'
    required: true
    default: ''
  repo:
    description: 'The repository.'
    required: true
    default: ''
  owner:
    description: 'The owner organization or user.'
    required: true
    default: ''
  authorName:
    description: 'Name of user with which the PR will be created.'
    required: false
    default: 'Github Action'
  authorEmail:
    description: 'Email address of the pull request creator.'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  projectNumber:
    description: 'The number of the project to use when issue is created.'
    required: false
    default: '0'
  pullRequestNumber:
    description: 'The number of the pull request that triggered this event.'
    required: false
    default: '0'
  issueNumber:
    description: 'The number of the issue that triggered this event.'
    required: false
    default: '0'
  statusOption:
    description: 'The status to set when moving an issue. This should contain any emojis.'
    required: false
  isOrganization:
    description: 'Indicate whether the user is an organization or a user. False if empty.'
    required: false
    default: ''
  disableComments:
    description: 'Disable Caretaker commenting back into the Pull Request.'
    required: false
    default: ''
  pullRequestProcessedLabel:
    description: 'The value of the label to apply to a pull request to mark it processed by Caretaker.'
    required: false
    default: 'caretaker-reviewed'
  scanInterval:
    description: 'The interval in which to check pull requests.'
    required: false
    default: '24h'
  commentID:
    description: 'The ID of the comment that handles a slash command. Used to add reaction to the comment.'
    required: false
    default: ''
  commentBody:
    description: 'The body of the comment.'
    required: false
    default: ''
  actor:
    description: 'The actor who performed the command. Used for assigning the user to the pr and related issues.'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    - --token=${{ inputs.token }}
    - --repo=${{ inputs.repo }}
    - --owner=${{ inputs.owner }}
    - --author-name=${{ inputs.authorName }}
    - --author-email=${{ inputs.authorEmail }}
    - --project-number=${{ inputs.projectNumber }}
    - --pull-request-number=${{ inputs.pullRequestNumber }}
    - --issue-number=${{ inputs.issueNumber }}
    - --status-option=${{ inputs.statusOption }}
    - --is-organization=${{ inputs.isOrganization }}
    - --pull-request-processed-label=${{ inputs.pullRequestProcessedLabel }}
    - --scan-interval=${{ inputs.scanInterval }}
    - --disable-comments=${{ inputs.disableComments }}
    - --comment-id=${{ inputs.commentID }}
    - --comment-body=${{ inputs.commentBody }}
branding:
  icon: "arrow-right-circle"
  color: purple
author: "Gergely Brautigam"
